In [1]:
from aggregator import attention
import convert_pca
import utils

In [9]:
import torch
delta={"a":torch.Tensor([[1,0,0],[0,0,0],[0,0,0]]),"b":torch.Tensor([[1,0,0],[0,0,0],[0,0,0]])}
deltas=[delta]*5
deltas[0]={"a":torch.Tensor([[0,1,0],[0,0,0],[0,0,0]]),"b":torch.Tensor([[1,0,0],[0,0,0],[0,0,0]])}
# result=attention.main(deltas)
# print(result)

In [10]:
stacked=utils.stackStateDicts(deltas)

In [11]:
convert_pca.net2vec(stacked).shape

torch.Size([18, 5])

In [12]:
stacked

{'a': tensor([[0., 1., 1., 1., 1.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 'b': tensor([[1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]])}

In [2]:
import torch

a=torch.Tensor([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [14]:
deltas

[{'a': tensor([[0., 1., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]),
  'b': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]])},
 {'a': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]),
  'b': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]])},
 {'a': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]),
  'b': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]])},
 {'a': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]),
  'b': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]])},
 {'a': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]),
  'b': tensor([[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]])}]

In [3]:
weight=torch.Tensor([1.0/5]*5)

In [7]:
weight[0].item()

0.20000000298023224

In [16]:
utils.applyWeight2StateDicts(deltas,weight)

{'a': tensor([[0.8000, 0.2000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]]),
 'b': tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])}

In [46]:
book=list(zip(deltas,weight))

sum([bookdeltas[i]['a'] for i in range(len(deltas))])

tensor([[4., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.stack([a]*5,-1).view(-1,5)[:,0]

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [8]:
a.flatten()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [9]:
! cd aggregator